### ISSUE TITLE
The question about the running the code

### ISSUE THREAD

**Issue by xingyushu** [euphoria0-0/Active-Client-Selection-for-Communication-efficient-Federated-Learning#3]
Hello,

When I ran the code as the guidance,I met the problem like this:

```
Current cuda device  0
Traceback (most recent call last):
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/main.py", line 136, in <module>
    data = load_data(args)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/main.py", line 31, in load_data
    return FederatedEMNISTDataset(args.data_dir, args)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/data/federated_emnist.py", line 20, in __init__
    self._init_data(data_dir)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/data/federated_emnist.py", line 29, in _init_data
    dataset = preprocess(data_dir, self.train_num_clients)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/data/federated_emnist.py", line 35, in preprocess
    train_data = h5py.File(os.path.join(data_dir, 'fed_emnist_train.h5'), 'r')
  File "/home/xingyu22/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/xingyu22/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../dataset/FederatedEMNIST/fed_emnist_train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

It means that I have no dataset? 

Will the code  download dataset  and save it as the ".h5" in the dataset dir?

Thanks so much,look forward to your reply at your convenience.

**Comment by euphoria0-0** [comment]
Thank you for your interest. I used this link [https://github.com/FedML-AI/FedML/blob/master/python/fedml/data/FederatedEMNIST/download_federatedEMNIST.sh]. I'll update it in README. :)

**Comment by xingyushu** [comment]
> Thank you for your interest. I used this link [https://github.com/FedML-AI/FedML/blob/master/python/fedml/data/FederatedEMNIST/download_federatedEMNIST.sh]. I'll update it in README. :)

Thanks so much
