### ISSUE TITLE
Question about the Trainer definition

### ISSUE THREAD

**Issue by xingyushu** [euphoria0-0/Active-Client-Selection-for-Communication-efficient-Federated-Learning#4]
Sorry for another question about your code:  

I set up the same env as yours:

torch=1.8.0
torchvision

And I met the missing  'loss_threshold'  attribute  in 'Trainer' object:

`> pre-client selection 10/3400
selected clients: [660, 1512, 2306, 2715, 2745, 2835, 2915, 2922, 3090, 3207]
Traceback (most recent call last):
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/main.py", line 152, in <module>
    ServerExecute.train()
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/FL_core/server.py", line 131, in train
    local_losses, accuracy, local_metrics = self.train_clients(client_indices)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/FL_core/server.py", line 255, in train_clients
    result = self.local_training(client_idx)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/FL_core/server.py", line 208, in local_training
    result = client.train(deepcopy(self.global_model))
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/FL_core/client.py", line 50, in train
    result = self.trainer.train(self.labeled_data)
  File "/home/xingyu22/FL_CSL/Active-Client-Selection-for-Communication-efficient-Federated-Learning/src/FL_core/trainer.py", line 73, in train
    if self.loss_threshold:
AttributeError: 'Trainer' object has no attribute 'loss_threshold'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
`

In the [Trainer class](https://github.com/euphoria0-0/Active-Client-Selection-for-Communication-efficient-Federated-Learning/blob/171b2cb7348c181bb84baa1487632bbf6408685d/src/FL_core/trainer.py) definiton,there is no the declareation of loss_threshold attribute and I can  not found it in the pytorch document,so how can I fix it or replace in another function?

Thanks.

**Comment by euphoria0-0** [comment]
Thank you for your comment. I fixed it.
